HEURISTIC_UNCONSTRAINED_MEM_ACCESS = True
CHECK_IF_MEM_ACCESS_IS_TOO_LARGE = True
ASK_FOR_LARGE_CONCRETIZATION = False
CHECK_DIVISION_BY_ZERO = False
SINGLE_LLIL_STEP = False
DONT_USE_SPECIAL_HANDLERS = False
SAVE_UNSAT = False
STACK_PAGE_SIZE = 4
USE_BN_JUMPTABLE_TARGETS = True
CONCRETIZE_MEM_ACCESSES = False

# models
ATOX_SLOW_MODEL = True
MAX_MALLOC = 0x1000
MAX_MEMCMP = 0x1000
MAX_MEMSET = 0x1000
MAX_SYMB_STR = 30
